config/routes.rb
Rails.application.routes.draw do

  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

  resources :tweets
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
	# The user in user_id is following the user in following_id
	belongs_to :user, :foreign_key => "user_id", :class_name => "User", counter_cache: :follow_count
	belongs_to :following, :foreign_key => "following_id", :class_name => "User", counter_cache: :followers
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	before_validation :link_check, on: :create

	validates :message, presence: true
	validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}, on: :create

	after_validation :apply_link, on: :create

	private

	def link_check
      check = false
      if self.message.include? "http://" 
          check = true
      elsif self.message.include? "https://"
          check = true
      else
          check = false
      end	
    
      if check == true
    	arr = self.message.split
    	index = arr.map{ |x| x.include? "http"}.index(true)
        self.link = arr[index]
        if arr[index].length > 23
    	    arr[index] = "#{arr[index][0..20]}..."	
        end
    				
        self.message = arr.join(" ")
      end
    end

    def apply_link
	  arr = self.message.split
	  index = arr.map { |x| x.include? "http" }.index(true)
	  if index
		url = arr[index]
		arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
	  end

	  self.message = arr.join(" ")
	end

end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true

  serialize :following, Array
  
  has_many :tweets

  has_many :follows, :foreign_key => "user_id", :class_name => "Follow"

  has_many :followings, :through => :follows

  mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  before_action :authenticate_user!
  before_action :set_following, only: [:feed, :all_users, :show_user, :following, :followers]

  def feed
  	@following_tweets = []
    @tweet = Tweet.new

    Tweet.all.order(created_at: :desc).each do |tweet|
      if @following.include?(tweet.user_id) || current_user.id == tweet.user_id
        @following_tweets.push(tweet)
      end
    end
  end

  def all_users
    @users = User.order(:username)
  end

  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
  	# Add the ID of the user to follow and current user's ID to Follow table
  	Follow.create(user_id: current_user.id, following_id: params[:id].to_i)

  	redirect_to show_user_path(id: params[:id])
  end

  def unfollow
  	@followship = Follow.where("user_id = ? AND following_id =?", current_user.id, params[:id].to_i).take
    @followship.destroy

  	redirect_to show_user_path(id: params[:id])
  end

  def following
    @user = User.find(params[:id])

    ids = Follow.where(user_id: @user.id).pluck(:following_id)
    @users = User.where(id: ids)

  end

  def followers
    @user = User.find(params[:id])
    
    ids = Follow.where(following_id: @user.id).pluck(:user_id)
    @users = User.where(id: ids)
  end
  
  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  private

  def set_following
    @following = Follow.where(user_id: current_user.id).pluck(:following_id)
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include TweetsHelper

  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def get_tagged(tweet)
		message_arr = tweet.message.split

	    message_arr.each_with_index do |word, index|
	      if word[0] == '#'
	        if Tag.pluck(:phrase).include?(word)
	          tag = Tag.find_by(phrase: word)
	        else
	          tag = Tag.create(phrase: word)
	        end
	        tweet_tag =TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
	        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
	      end
	    end

	    tweet.message = message_arr.join(" ")
	    return tweet
	end
end

app/views/epicenter/_profile.html.erb
<%= image_tag user.avatar.url, size: 100 %>
<h3>@<%= user.username %></h3>
<p><%= user.name %></p>
<p><%= user.location %></p>
<p><%= user.bio %></p>

app/views/epicenter/_stats.html.erb
<ul class="list-inline">
  <li>
  	<%= link_to following_path(id: user.id) do %>
  	<p class="text-muted">Following</p>
  	<h4 class="text-primary"><%= user.follow_count ||= 0 %></h4>
  	<% end %>
  </li>
  <li>
  	<%= link_to followers_path(id: user.id) do %>
  	<p class="text-muted">Followers</p>
  	<h4 class="text-primary"><%= user.followers ||= 0 %></h4>
  	<% end %>
  </li>
  <li>
  	<%= link_to show_user_path(id: user.id) do %>
  	<p class="text-muted">Tweets</p>
  	<h4 class="text-primary"><%= user.tweets.count %></h4>
  	<% end %>
  </li>
</ul>

app/views/epicenter/_user_list.html.erb
<% @users.each do |user| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class='col-md-3'>
        <%= image_tag user.avatar.url, class: "user-pic-md img-responsive" %>
      </div>
      <div class='col-md-3'>
        <%= link_to show_user_path(id: user.id) do %>
          <h3><%= user.name %></h3>
          <p>@<%= user.username %></p>
        <% end %>
        <p><%= user.bio %></p>
      </div>
      <span class='pull-right'>
        <% if current_user.id != user.id %>
      	  <% if @following.include?(user.id) %>
            <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
          <% else %>
              <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </span>
    </div>
  </div>
<% end %>

app/views/epicenter/all_users.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'user_list' %>
  </div>
</div>

app/views/epicenter/feed.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'profile', user: current_user %>
        <%= render 'stats', user: current_user %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
  	<div class="panel panel-info">
      <div class="panel-body">
      <%= render 'tweets/form', tweet: @tweet %>
      </div>
    </div>
    <% @following_tweets.each do |tweet| %>
  	  <%= render 'tweets/tweet', tweet: tweet %>
    <% end %>
  </div>
</div>

app/views/epicenter/followers.html.erb
<h2>@<%= @user.name %>'s followers:</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= render 'user_list' %>
  </div>
</div>

app/views/epicenter/following.html.erb
<h2>@<%= @user.username %> is following:</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= render 'user_list' %>
  </div>
</div>

app/views/epicenter/show_user.html.erb
<div class="row">
  <div class="col-md-3">
  	<%= render 'profile', user: @user %>
  </div>
  <div class="col-md-6">
  	<div class="panel panel-default">
  	  <div class="panel-body">
  	    <%= render 'stats', user: @user %>
  		<p class='pull-right'>
		  <% if @following.include?(@user.id) %>
		    <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
		  <% else %>
		    <% if current_user.id != @user.id %>
			  <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
			<% end %>
		  <% end %>
		</p>
	  </div>
	</div>
  	<% @user.tweets.each do |tweet| %>
	  <%= render 'tweets/tweet', tweet: tweet %>
	<% end %>
  </div>
</div>

app/views/epicenter/tag_tweets.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <h1><%= @tag.phrase %></h1>
    <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
       <%= render 'tweets/tweet', tweet: tweet %>
    <% end %>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  </head>

  <body>
	  <nav class="navbar navbar-default">
	    <div class="container-fluid">
	      <!-- Brand and toggle get grouped for better mobile display -->
	      <div class="navbar-header">
	        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	          <span class="sr-only">Toggle navigation</span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	        <%= link_to "Home", root_path, class: "navbar-brand" %>
	      </div>
	      <!-- Collect the nav links, forms, and other content for toggling -->
	      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	        <ul class="nav navbar-nav">
	          <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
	          <li><%= link_to "All Users", all_users_path %></li>
	        </ul>
	        <ul class="nav navbar-nav navbar-right">
	          <% if user_signed_in? %>
	            <li class="dropdown">
	              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	                <% if current_user.avatar.blank? == false %>
	                  <%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav" %>
	                <% end %> 
	                @<%= current_user.username %> <span class="caret"></span></a>
	              <ul class="dropdown-menu">
	                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	              </ul>
	            </li>
	          <% end %>
	        </ul>
	      </div>
	    </div>
	  </nav>
	  <div class="container">
	    <%= yield %>
	  </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= form.text_field :message, placeholder: "What's happening?", class: "form-control", id: "tweet-text" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <!-- display remaining characters in tweet -->
  <span id="char-remain"></span>
  
  <div class="form-group pull-right">
    <%= form.submit "Tweet It!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="panel panel-default">
  <div class="panel-body">
  	<%= link_to show_user_path(id: tweet.user.id) do %>
  	  <%= image_tag tweet.user.avatar.url, size: 50 %>
  	  <span class='text-primary'><%= "@#{tweet.user.username}" %></span>
  	  <span class='text-muted'>
  	     • <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 1.day %>
  	    <%= tweet.created_at.strftime('%b %e') if Time.now - tweet.created_at > 1.day %>
  	  </span>
  	<% end %>
    <p><%= tweet.message.html_safe %></p>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <h1>All Tweets</h1>
    <% @tweets.order(id: :desc).each do |tweet| %>
      <%= render 'tweet', tweet: tweet %>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Tweet', new_tweet_path %>a

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<div id = 'row'>
  <div id = 'col-md-6 col-md-offset-3'>
	<%= render 'tweet', tweet: @tweet %>
  </div>
</div>

<% if @tweet.user.id == current_user.id %>
  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<% end %>
<%= link_to 'Back', tweets_path %>